version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    container_name: dms-app
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
      - minio
      - elasticsearch
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dmsdb
      SPRING_RABBITMQ_HOST: rabbitmq
    env_file:
        - environment.env
    networks:
      - dms-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dms-frontend
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - dms-network

  postgres:
    image: postgres:15
    container_name: dms-db
    restart: always
    environment:
      POSTGRES_DB: dmsdb
    env_file:
      - environment.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dms-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: dms-mq
    ports:
      - "5672:5672"
      - "9093:15672"
    env_file:
      - environment.env
    networks:
      - dms-network

  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - environment.env
    ports:
      - "9000:9000"
      - "9090:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - dms-network

  ocr-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.ocr
    container_name: dms-ocr-worker
    depends_on:
      - rabbitmq
      - minio
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      MINIO_ENDPOINT: minio:9000
      SPRING_PROFILES_ACTIVE: ocr
    env_file:
      - environment.env
    networks:
      - dms-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
    env_file:
      - environment.env
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - dms-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.28
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    env_file:
      - environment.env
    ports:
      - "5601:5601"
    networks:
      - dms-network
    depends_on:
      - elasticsearch

  adminer:
    image: adminer:latest
    container_name: dms-adminer
    restart: always
    ports:
      - "9091:8080"
    networks:
      - dms-network


networks:
  dms-network:
    driver: bridge

volumes:
  minio_data:
    name: minio_data
    driver: local
  postgres_data:
    name: postgres_data
    driver: local
  elasticsearch_data:
    driver: local