version: '3.8'

services:
  # API Service
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    container_name: dms-app
    ports:
      - "8081:8081"  # Exposes the application on port 8081 (host:container)
    depends_on:
      - postgres  # Waits for PostgreSQL to be ready before starting
      - rabbitmq  # Waits for RabbitMQ to be ready before starting
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dmsdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - dms-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dms-frontend
    ports:
      - "80:80"  # Serve on port 80
    depends_on:
      - app
    networks:
      - dms-network

  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: dms-db
    restart: always
    environment:
      POSTGRES_DB: dmsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dms-network

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: dms-mq
    ports:
      - "5672:5672"  # RabbitMQ communication
      - "9093:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    networks:
      - dms-network

  # MinIO Service
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000" # MinIO
      - "9090:9001" # MinIO Console
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - dms-network

  # OCR Worker Service
  ocr-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.ocr  # Reference the OCR-specific Dockerfile
    container_name: dms-ocr-worker
    depends_on:
      - rabbitmq  # The OCR worker may be waiting for RabbitMQ to be available
      - minio     # If OCR interacts with MinIO for file storage
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      MINIO_ENDPOINT: minio:9000  # MinIO connection info
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      SPRING_PROFILES_ACTIVE: ocr  # Activate the OCR profile
    networks:
      - dms-network


  # Elasticsearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true  # Enable security
      - ELASTIC_PASSWORD=yourpassword  # Set the password for the "elastic" superuser (or the default user)
      - ELASTICSEARCH_USERNAME=elastic  # You can still use "elastic" for other purposes
    ports:
      - "9200:9200"  # REST API
      - "9300:9300"  # Internal communication
    networks:
      - dms-network  # Network name here

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.28
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Connect Kibana to Elasticsearch
      - ELASTICSEARCH_USERNAME=elastic  # Username for authentication
      - ELASTICSEARCH_PASSWORD=yourpassword  # Password for authentication
    ports:
      - "5601:5601"
    networks:
      - dms-network  # Network name here
    depends_on:
      - elasticsearch


networks:
  dms-network:
    driver: bridge

volumes:
  minio_data:
    name: minio_data
    driver: local
  postgres_data:
    name: postgres_data
    driver: local
