FROM openjdk:17-jdk-slim AS build

RUN apt update && apt install -y tesseract-ocr libtesseract-dev

RUN apt-get update && \
    apt-get install -y ghostscript ca-certificates && \
    apt-get clean

WORKDIR /app

COPY target/ocr/*.jar app-ocr-worker.jar

ENTRYPOINT ["java", "-jar", "/app/app-ocr-worker.jar"]

EXPOSE 8082
